---
abstract: "a CPAN distribution to handle the various formats that\nPerl module names and distribution names are kept in."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  vars: 0
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3617'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Format
provides:
  Module::Format:
    file: lib/Module/Format.pm
    version: v0.0.1
  Module::Format::Module:
    file: lib/Module/Format/Module.pm
    version: v0.0.1
  Module::Format::ModuleList:
    file: lib/Module/Format/ModuleList.pm
    version: v0.0.1
  Module::Format::PerlMF_App:
    file: lib/Module/Format/PerlMF_App.pm
    version: v0.0.1
requires:
  Getopt::Long: 2.36
  List::MoreUtils: 0
  Pod::Usage: 0
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.1
